---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  always_update_cookbooks: true
verifier:
  name: inspec
platforms:
  - name: ubuntu-16.04
    driver_config:
      run_command: /bin/systemd
      privileged: true
  - name: ubuntu-18.04
    driver_config:
      run_command: /bin/systemd
      privileged: true
      provision_command:
        - apt-get install -y net-tools gnupg
  - name: centos-7
    driver_config:
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - systemctl enable sshd.service
suites:
  - name: default
    run_list:
      - recipe[custom_nginx::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
