---
driver:
  name: docker
  use_sudo: false
  run_options:
    net: chefnetwork
  instance_name: centos-7

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  product_name: chef
  product_version: 13.9.4

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - systemctl enable sshd.service

suites:
  - name: default
    run_list:
      - recipe[redis::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
